config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/about', to: 'about#index', as: :about

  resources :users, only: [:new, :create]
  resources :search, only: [:index, :new]
  resources :celestial_bodies, only: [:show] do
    resources :telescope, only: [:create]
  end


  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'auth/google_oauth2/callback', to: 'sessions#create'

  resources :iss_search, only: [:index, :new]
  get '/iss_alerts', to: 'iss_alerts#create'

  get '/geocode', to: 'geocode#show'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/celestial_bodies_controller.rb
class CelestialBodiesController < ApplicationController
  def show
    render locals: {
      facade: CelestialBodyFacade.new(params)
    }
  end
end

app/views/celestial_bodies/show.html.erb
<div class="body-container" style="background-image: url('<%= facade.image %>')">
  <div class="body-box">
    <h1><%= facade.name %></h1>
    <div class="tracking-button body-description">
      <%= form_for :telescope, url: celestial_body_telescope_index_path(celestial_body_id: facade.body), method: :post do |f| %>
        <%= f.hidden_field(:location, :value => facade.user_location) %>
        <%= f.label :ngrok_url, "My Telescope's Address:" %>
        <%= f.text_field :ngrok_url %>
        <%= f.submit "Point My Telescope at #{facade.name}" %>
        <%= f.submit "Test" %>
      <% end %>
    </div>
    <div class="body-description">
        <p><%= facade.description %></p>
    </div>
  </div>
</div>