config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/about', to: 'about#index', as: :about

  resources :users, only: [:new, :create]
  resources :search, only: [:index, :new]
  resources :celestial_bodies, only: [:show] do
    resources :telescope, only: [:create]
  end


  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'auth/google_oauth2/callback', to: 'sessions#create'

  resources :iss_search, only: [:index, :new]
  get '/iss_alerts', to: 'iss_alerts#create'

  get '/geocode', to: 'geocode#show'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def new
    PingSkyfieldJob.perform_async
  end

  def index
    if params[:button] == "planet_search"
      @facade = SearchResultsFacade.new(search_params)
    elsif params[:button] == "iss_search"
      @facade = IssSearchResultFacade.new(iss_search_params)
    end
  end

  private

  def search_params
    if valid_search?
      session[:location] = params[:location]
      params.permit(:location, :button, bodies:[])
    else
      render :new
    end
  end

  def valid_search?
    if valid_bodies? && valid_location?
      true
    elsif !valid_bodies?
      flash.now[:errors] = "Must select at least one celestial body"
      false
    elsif !valid_location?
      flash.now[:errors] = "Invalid location entry, please try again"
      false
    end
  end

  def valid_bodies?
    params[:bodies].present?
  end

  def valid_location?
    mapbox = MapboxService.new(params[:location])

    params[:location].present? && mapbox.valid?
  end

  def iss_search_params
    if valid_location?
      params.permit(:location, :button)

    else
      flash[:errors] = "Invalid location entry, please try again"
      render :new
    end


  end

end

app/views/search/index.html.erb
<% if params[:button] == "planet_search" %>
<h1>Search Results</h1>
<section class="search-results">
  <h4>My Location: <%= @facade.user_estimated_location %></h4>
  <h4 id="search-time">Search Time: <%= local_time(@facade.search_time) %></h4>
  <div class="results">
    <% @facade.body_results.each do |body| %>
      <section class="celestial-body">
        <div class="body-link">
          <%=link_to body.name, celestial_body_path(body.name, location: @facade.user_telescope_location) %>
        </div>
        <div class="body-angles">
          Just looking or using a traditional telescope?<br>
          Use these coordinates:<br><br>
          Azimuth <%= body.user_az %>  <br>
          Elevation <%= body.user_el %> <br><br>
          <% if body.el_messaging > 0 %>
            To see <%= body.name %>, turn <%= body.az_messaging %><br>
            And use your hand to measure <%= body.el_messaging %> fingers above the horizon.<br><br>
          <% else %>
            <%= body.name %> is currently below the horizon.<br><br>
          <% end %>
          Using a telescope with an equatorial mount?<br>
          Use these coordinates:<br><br>
          Right Ascension <%= body.user_ra %> <br>
          Declination <%= body.user_dec %> <br><br>
        </div>
      </section>
    <% end %>
  </div>
  <section class="help">
    <p>For more help finding elevation or using your telescope, please see our <%= link_to "About", about_path %> page.</p>
  </section>

  <div class="search-and-refresh">
    <div class="new-search">
      <%= button_to "New Search", new_search_path, method: :get %>
    </div>

    <div class="refresh-search">
      <input type="button" name="refresh" value="Refresh" onClick= "window.location.reload();" >
    </div>
  </div>
  <div class="weather">
    <% @facade.weather.each do |hour| %>
    <section class='hourly_weather'>
      <div class="hour_weather">
        <ul>
          <li><%= local_time(hour.time, '%I %p') %></li>
          <li><%= image_tag hour.icon %></li>
          <li><%= hour.summary %></li>
          <li>Temperature: <%= hour.temperature %>°</li>
          <li>Cloud Coverage: <%= hour.cloud_cover_percentage %>%</li>
          <li>Chance of Rain: <%= hour.precipProbability %>%</li>
        </ul>
      </div>
    </section>
    <% end %>
  </div>
</section>

<% else %>

<h1>Find the International Space Station</h1>
<div class="iss-search-result-container">
  <div class="iss-search-result">
    <p>Search location: <%= @facade.user_estimated_location %></p>
    <p>Time of search: <%= local_time(@facade.time_of_search) %></p>

    <p>Next Rise Time: <%= local_time(@facade.next_rise_time) %></p>
    <p>Duration: <%= @facade.duration %> minutes </p>
  </div>
</div>
<div class="text-alert-container">
  <div class="text-alert-form">
    <%= form_tag('/iss_alerts', method: :get) do %>
      <label for="phone">Enter your phone number to schedule a text message alert 15 mins prior to next rise time (<%= local_time(@facade.next_rise_time - (15 * 60)) %>):</label>

      <input type="tel" id="phone" name="phone"
        pattern="[0-9]{10}"
        placeholder="Format: 1234567890"
        title="Format: 1234567890"
        required>

      <%= hidden_field_tag :rise_time, @facade.next_rise_time %>
      <%= hidden_field_tag :location, @facade.mapbox_long_lat %>
      <p id='submit'>
        <%= submit_tag("Schedule text message") %>
      </p>
    <% end %>
  </div>
</div>

<% end %>

app/views/search/new.html.erb
<div class="search-box">
  <section class='search-body-box'>
    <%= form_tag('/search', method: :get) do %>

      <div id="location-search-box">
        <h1 id="location-header">Enter Your Location</h1>
        <h5 id="pin-header">Or click pin to use browser location</h5>
        <div class="location-search">
          <input type="input-field" name="location" title="location" id="location" placeholder="A street address, A city or neighborhood, A postal code, A point of interest" class="location-field" value="<%= session[:location] %>"></input>
          <br />
          <%=image_tag('pin.green.png', id: 'browser-location', class: 'location-default') %>
        </div>
        <p id='status'></p>
      </div>

      <h1>Find a Celestial Body</h1>

      <div class="body-choices">
        <% celestial_bodies.each do |body| %>
            <div class='check-box'%>
              <%= check_box_tag 'bodies[]', body.name %>
              <%= label_tag body.name %>
            </div>
        <% end %>

      </div><br />

      <p id='submit'>
        <%= button_tag "Planet Search" , value: :planet_search %>
      </p>


      <h1>Find the International Space Station</h1>
      <p id='submit'>
        <%= button_tag "Find ISS" , value: :iss_search %>
      </p>

    <% end %>
  </section>
</div>